const data = [ // 0: 没去过 1: 去过1次 2: 去过几次 3: 经常去
  { name: '中国', degree: 3 },
  { name: '安徽省', degree: 1 },
  { name: '澳门特别行政区', degree: 3 },
  { name: '北京市', degree: 1 },
  { name: '重庆市', degree: 1 },
  { name: '福建省', degree: 0 },
  { name: '甘肃省', degree: 0 },
  { name: '广东省', degree: 3 },
  { name: '广西壮族自治区', degree: 0 },
  { name: '贵州省', degree: 0 },
  { name: '海南省', degree: 0 },
  { name: '南海诸岛', degree: 0 },
  { name: '河北省', degree: 0 },
  { name: '河南省', degree: 0 },
  { name: '黑龙江省', degree: 0 },
  { name: '湖北省', degree: 3 },
  { name: '湖南省', degree: 2 },
  { name: '吉林省', degree: 0 },
  { name: '江苏省', degree: 2 },
  { name: '江西省', degree: 1 },
  { name: '辽宁省', degree: 0 },
  { name: '内蒙古自治区', degree: 0 },
  { name: '宁夏回族自治区', degree: 0 },
  { name: '青海省', degree: 0 },
  { name: '山东省', degree: 0 },
  { name: '山西省', degree: 0 },
  { name: '陕西省', degree: 1 },
  { name: '上海市', degree: 1 },
  { name: '四川省', degree: 1 },
  { name: '台湾省', degree: 1 },
  { name: '天津市', degree: 0 },
  { name: '西藏自治区', degree: 0 },
  { name: '香港特别行政区', degree: 3 },
  { name: '新疆维吾尔自治区', degree: 0 },
  { name: '云南省', degree: 0 },
  { name: '浙江省', degree: 3 },
];

export default data;
